# Generated by Django 5.0.6 on 2024-06-18 16:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('date', models.DateField()),
                ('word', models.CharField(max_length=100)),
                ('game_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField()),
                ('entered_words', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('hints', models.PositiveIntegerField()),
                ('guessed', models.BooleanField(default=False)),
            ],
        ),
    ]
